version: 2
mergeable:
  - when: pull_request.*
    filter:
      - do: author
        must_exclude:
          regex: 'dependabot'
    validate:
      - do: description
        must_include:
          regex: 'https://forto.atlassian.net/\w+/[A-Z][A-Z0-9]+-\d+'
          message: 'Must include Jira ticket'

