version: 2
mergeable:
  - when: pull_request.*
    filter:
      - do: author
        must_exclude:
          regex: 'dependabot'
    validate:
      - do: description
        must_include:
          regex: '((?<!([A-Z]{1,10})-?)[A-Z]+\d?-\d+)'
          message: 'Must include Jira ticket'

